### PR TITLE
better rebar3 integration

### LINKED ISSUE #141: rebar3: First incarnation ends in function clause error after intallation
Saw your posting on Elixir forums. I am close to completing a small project so I thought  I would give it a try.
I added the plugin to rebar.config as instructed, did a rebar3 clean and it installed the plugin fine.
Sadly it blew as soon as I tried this on...

```
sean@Seans-iMac ~/D/c/e/scofblog> rebar3 --version                                                                                    1 master!?
rebar 3.13.2 on Erlang/OTP 23 Erts 11.0.3
```

Here is the output:

```
sean@Seans-iMac ~/D/c/e/scofblog> rebar3 fmt -o fmt src/*.erl        2 master!?
rebar3 fmt Internal Error
error:function_clause
[{erlfmt_cli,parse_opts,
             [[{task,"src/activate_impl.erl"}],
              "rebar3 fmt",
              ["src/activate_h.erl","src/utils.erl","src/scofblog_sup.erl",
               "src/scofblog_app.erl","src/newcomment_impl.erl",
               "src/newcomment_h.erl","src/messages.erl","src/mails.erl",
               "src/dbms.erl","src/comment_impl.erl","src/comment_h.erl",
               "src/approve_impl.erl","src/approve_h.erl"],
              {config,false,undefined,ignore,{path,<<"fmt">>}}],
             [{file,"/Users/sean/Documents/code/erlang/scofblog/_build/default/plugins/erlfmt/src/erlfmt_cli.erl"},
              {line,90}]},
 {erlfmt_cli,do_unprotected,2,
             [{file,"/Users/sean/Documents/code/erlang/scofblog/_build/default/plugins/erlfmt/src/erlfmt_cli.erl"},
              {line,57}]},
 {erlfmt_cli,do,2,
             [{file,"/Users/sean/Documents/code/erlang/scofblog/_build/default/plugins/erlfmt/src/erlfmt_cli.erl"},
              {line,48}]},
 {rebar3_fmt_prv,do,1,
                 [{file,"/Users/sean/Documents/code/erlang/scofblog/_build/default/plugins/erlfmt/src/rebar3_fmt_prv.erl"},
                  {line,45}]},
 {rebar_core,do,2,
             [{file,"/private/tmp/rebar3-20200430-34521-rdyweb/rebar3-3.13.2/src/rebar_core.erl"},
              {line,154}]},
 {rebar3,run_aux,2,
         [{file,"/private/tmp/rebar3-20200430-34521-rdyweb/rebar3-3.13.2/src/rebar3.erl"},
          {line,182}]},
 {rebar3,main,1,
         [{file,"/private/tmp/rebar3-20200430-34521-rdyweb/rebar3-3.13.2/src/rebar3.erl"},
          {line,66}]},
 {init,start_em,1,[]}]
sean@Seans-iMac ~/D/c/e/scofblog>
```

### LINKED ISSUE #177: rebar3: `rebar3 fmt` execution priority
I have the following in `rebar.config`:
```erlang
{erlfmt, [
    write,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
I ran `erlfmt` and starting staging changes in Git, for further commit and push. The ones I don't like, I discard.

I saw that I wanted to redo formatting on a single file so I did `rebar3 fmt <file>`.

To my surprise all files were formatted again. Is this the expectation, or should `files` (from `rebar.config`) be ignored, if `<file>` is present in the CLI?

### PR DESCRIPTION
**Pull request by awalterschulze**
This gives command line arguments preference over arguments specified in the rebar3 config.

This Fixes #177
And fixes #141

## Test Plan:

Given the following config

```erlang
{erlfmt, [
    write,
    {files, "{src,include,test}/*.{hrl,erl}"}
]}.
```

```sh
rebar3 fmt # formats all files in place
rebar3 fmt ./src/example.app.src # only formats the single file
rebar3 fmt --check # checks all files and doesn't format
rebar3 fmt -o ./out/ # outputs formatted files folder and doesn't format the original
rebar3 fmt -o out src/*.erl # formats only selected files and outputs them to selected folder
```

### Tested with incorrect config

```
{erlfmt, [
    check,
    require_pragma,
    verbose,
    {width, 100},
    {files, ["{src,include,test}/*.{hrl,erl,app.src}", "rebar.config"]}
]}.
```

Got error:
```
unknown option: {width,100}

Usage: rebar3 fmt [-h] [-v] [-w] [-o <out>] [--verbose] [-c]
                  [--print-width <print_width>] [--require-pragma]
                  [--insert-pragma] [<files>]
```

### CODE REVIEW

File: src/erlfmt_cli.erl [hunk 1]
```diff
@@ -196,51 +225,103 @@ read_stdin(Data) ->
...
-    parse_opts(Rest, Name, Files, Config#config{pragma = insert});
-parse_opts([{files, NewFiles} | Rest], Name, Files0, Config) ->
-    parse_opts(Rest, Name, expand_files(NewFiles, Files0), Config);
-parse_opts([], _Name, [stdin], #config{out = Out}) when Out =/= standard_out, Out =/= check ->
+parse_opts([insert_pragma | Rest], Files, Config) ->
+    parse_opts(Rest, Files, Config#config{pragma = insert});
+parse_opts([{files, NewFiles} | Rest], Files0, Config) ->
+    parse_opts(Rest, expand_files(NewFiles, Files0), Config);
+parse_opts([], [stdin], #config{out = Out}) when
+    Out =/= standard_out, Out =/= undefined, Out =/= check
```
Comment (michalmuskala) [inline src/erlfmt_cli.erl:263]: Can `Out` ever be `standard_out` now?

File: src/erlfmt_cli.erl [hunk 2]
```diff
@@ -196,51 +225,103 @@ read_stdin(Data) ->
...
+    #config{
+        verbose = PreferVerbose orelse DefaultVerbose,
+        width = resolve_width(PreferWidth, DefaultWidth),
+        pragma = resolve_pragma(PreferPragma, DefaultPragma),
+        out = resolve_out(PreferOut, DefaultOut)
+    }.
+
+resolve_width(undefined, W) -> W;
+resolve_width(W, undefined) -> W;
+resolve_width(W, _) -> W.
```
Comment (michalmuskala) [inline src/erlfmt_cli.erl:315]: In this case the middle clause is not needed. The following would behave the same, bur perhaps it's clearer to have the extra clause, I'm not sure
```suggestion
resolve_width(undefined, W) -> W;
resolve_width(W, _) -> W.
```

File: src/erlfmt_cli.erl [hunk 3]
```diff
@@ -196,51 +225,103 @@ read_stdin(Data) ->
...
+
+resolve_pragma(ignore, P) -> P;
+resolve_pragma(P, ignore) -> P;
+resolve_pragma(P, _) -> P.
```
Comment (michalmuskala) [inline src/erlfmt_cli.erl:319]: Similar here

File: src/erlfmt_cli.erl [hunk 4]
```diff
@@ -196,51 +225,103 @@ read_stdin(Data) ->
...
+
+resolve_out(undefined, O) -> O;
+resolve_out(O, undefined) -> O;
+resolve_out(O, _) -> O.
```
Comment (michalmuskala) [inline src/erlfmt_cli.erl:323]: And here

File: src/erlfmt_cli.erl [hunk 5]
```diff
@@ -48,19 +50,34 @@ opts() ->
...
+    PreferParsed = parse_opts(PreferOpts),
+    DefaultParsed = parse_opts(DefaultOpts),
+    Parsed = resolve_parsed(PreferParsed, DefaultParsed),
+    with_parsed(Name, Parsed).
+
+-spec with_parsed(string(), parsed()) -> ok.
+with_parsed(Name, Config) ->
     try
-        do_unprotected(Opts, Name)
+        unprotected_with_config(Name, Config)
```
Comment (michalmuskala) [inline src/erlfmt_cli.erl:67]: Before parsing was also protected inside the try, I'm not sure if it's important, but perhaps we should keep it. What do you think?

File: src/erlfmt_cli.erl (hunk 1 above)
Comment (awalterschulze) [reply src/erlfmt_cli.erl:263]: I do not know what I was thinking.
I got confused with `-o`
I will remove `undefined`
Sorry about that.

File: src/erlfmt_cli.erl (hunk 5 above)
Comment (awalterschulze) [reply src/erlfmt_cli.erl:67]: parse_opts is now a pure and total function, so I hope we can get away without the catch and rather fix the bugs when we encounter an unexpected case.

Comment (awalterschulze) [reply src/erlfmt_cli.erl:67]: I added an extra manual test for this case

**Review by michalmuskala — APPROVED** [review]
This is a great improvement!
