### PR TITLE
do not crash when formatting an empty file

### LINKED ISSUE #126: Crash on a completely empty file
Steps to reproduce
```
$ touch test.erl
$ erlfmt test.erl
```
Result
```
=ERROR REPORT==== 2-Sep-2020::14:46:41.373220 ===
Error in process <0.70.0> with exit value:
{function_clause,[{erlfmt,read_nodes,
                          [{eof,{1,1}},"test.erl",ignore],
                          [{file,"/Users/walterschulze/code/src/github.com/WhatsApp/erlfmt/src/erlfmt.erl"},
                           {line,213}]},
                  {erlfmt,read_file,2,
                          [{file,"/Users/walterschulze/code/src/github.com/WhatsApp/erlfmt/src/erlfmt.erl"},
                           {line,192}]},
                  {erlfmt,format_file,3,
                          [{file,"/Users/walterschulze/code/src/github.com/WhatsApp/erlfmt/src/erlfmt.erl"},
                           {line,67}]},
                  {erlfmt_cli,format_file,2,
                              [{file,"/Users/walterschulze/code/src/github.com/WhatsApp/erlfmt/src/erlfmt_cli.erl"},
                               {line,76}]},
                  {erlfmt_cli,'-parallel_loop/5-fun-0-',2,
                              [{file,"/Users/walterschulze/code/src/github.com/WhatsApp/erlfmt/src/erlfmt_cli.erl"},
                               {line,155}]}]}
```

### PR DESCRIPTION
**Pull request by awalterschulze**
Fixes #126

### CODE REVIEW

File: src/erlfmt.erl [hunk 1]
```diff
@@ -292,28 +292,34 @@ node_string(Cont) ->
...
     {raw_string, Anno, string:trim(String, both, "\n")}.
 
-format_nodes([{attribute, _, {atom, _, spec}, _} = Attr, {function, _, _} = Fun | Rest], PageWidth) ->
+format_nodes([], _PageWidth) ->
+    [];
+format_nodes(Nodes, PageWidth) ->
+    [$\n | Formatted] = format_nodes_helper(Nodes, PageWidth),
+    Formatted.
+
+format_nodes_helper([{attribute, _, {atom, _, spec}, _} = Attr, {function, _, _} = Fun | Rest], PageWidth) ->
```
Comment (michalmuskala) [inline src/erlfmt.erl:301]: How about `format_nodes_loop` for the name here?

**Review by michalmuskala — APPROVED** [review]
Good solution!

File: src/erlfmt.erl (hunk 1 above)
Comment (awalterschulze) [reply src/erlfmt.erl:301]: Can do 👍
